spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.61/sell?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.43.61
    port: 6379
server:
  port: 80
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level: error
wechat:
  mpAppId: wx4cb7ca4404191ff3
  mpAppSecret: 66842f86adc5b679ca6d40c17cf1791a
  openAppId:
  openAppSercet:
  mchId: 1409146202
  mchKey: c976503d34ca432c60131f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sea.mynatapp.cc/sell/pay/notify
  templateId:
    orderStatus:

#  wx746b904d434a628e
#  b5021632a75fdc56d15eb4b3baa35588

projectUrl:
  wechatMpAuthorize: http://sea.mynatapp.cc
  wechatOpenAuthorize: http://sea.mynatapp.cc
  sell: http://sea.mynatapp.cc
logging:
  level:
    com.sea.sell.entity.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
